name: buchouchi
description: A Flutter Android app for Chinese cuisines recipes with ingredient checklists.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path: ^1.9.0
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes/seed_more.json
    - assets/recipes/images.json       # ⬅️ 映射表（CI 会自动生成/更新）
    - assets/recipes/seed_names.txt    # ⬅️ 料理名清单（我们提供初始版本）
    - assets/images/                   # ⬅️ 本地图片目录（CI 会把图片存进来）
