name: Android CI (Flutter)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      target_ref:
        description: "Branch or tag to build (e.g. main / feature/x / v1.0.0)"
        required: false
        default: ""

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_ref != '' && github.event.inputs.target_ref || github.ref }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Clean build
        run: flutter clean

      # 仅重建 android 宿主（不动 lib/）
      - name: Regenerate Android host only
        run: |
          set -euo pipefail
          flutter create . \
            --platforms=android \
            --org com.example \
            --project-name buchouchi \
            --overwrite
          XML="android/app/src/main/res/values/strings.xml"
          if [ -f "$XML" ]; then
            sed -i 's#<string name="app_name">[^<]*</string>#<string name="app_name">不愁吃</string>#g' "$XML"
          fi

      # 打印当前构建的提交以及 main.dart 头部，方便核对
      - name: Debug - print ref and main.dart head
        run: |
          set -e
          echo "REF: $GITHUB_REF  SHA: $GITHUB_SHA"
          echo "---- lib/main.dart (head) ----"
          sed -n '1,120p' lib/main.dart || true

      # ✅ 保底：若检测到模板痕迹，改用 printf 生成正确的 main.dart（避免 heredoc 缩进问题）
      - name: Autofix - replace template main.dart if detected (no heredoc)
        run: |
          set -e
          if grep -qE "Flutter Demo Home Page|MyHomePage" lib/main.dart; then
            echo "Template detected. Replacing lib/main.dart with BuchouChi entry..."
            printf "%s\n" \
              "import 'package:flutter/material.dart';" \
              "import 'db/database_helper.dart';" \
              "import 'pages/home_page.dart';" \
              "" \
              "void main() async {" \
              "  WidgetsFlutterBinding.ensureInitialized();" \
              "  await DatabaseHelper.instance.db;" \
              "  runApp(const BuchouChiApp());" \
              "}" \
              "" \
              "class BuchouChiApp extends StatelessWidget {" \
              "  const BuchouChiApp({super.key});" \
              "" \
              "  @override" \
              "  Widget build(BuildContext context) {" \
              "    return MaterialApp(" \
              "      title: '不愁吃'," \
              "      theme: ThemeData(" \
              "        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF4CAF50))," \
              "        useMaterial3: true," \
              "      )," \
              "      home: const HomePage()," \
              "    );" \
              "  }" \
              "}" \
              > lib/main.dart
            echo "---- lib/main.dart (after autofix, head) ----"
            sed -n '1,120p' lib/main.dart
          fi

      # 再做一次护栏，确保模板已清除且关键文件存在
      - name: Guard - ensure template removed
        run: |
          set -e
          if grep -R --line-number -E "Flutter Demo Home Page|MyHomePage" lib/ ; then
            echo "::error title=Template app detected::Your lib/ still contains the Flutter demo template after autofix."
            exit 1
          fi
          test -f lib/pages/home_page.dart || { echo "::error title=Missing file::lib/pages/home_page.dart not found."; exit 1; }
          test -f lib/db/database_helper.dart || { echo "::error title=Missing file::lib/db/database_helper.dart not found."; exit 1; }

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: buchouchi-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
