name: Android CI (Flutter)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Clean build
        run: flutter clean

      - name: Guard - ensure no Android v1 embedding
        shell: bash
        run: |
          set -euo pipefail
          # 检查是否存在 v1 embedding 的典型痕迹
          if grep -R --line-number --fixed-strings "io.flutter.app" android/ ; then
            echo "::error title=Deprecated Android v1 embedding detected::Found 'io.flutter.app' imports."
            exit 1
          fi
          if grep -R --line-number --fixed-strings "FlutterMain" android/ ; then
            echo "::error title=Deprecated Android v1 embedding detected::Found 'FlutterMain' usages."
            exit 1
          fi
          echo "No Android v1 embedding traces found."

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: buchouchi-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
