name: Android CI (Flutter)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      # 1) 清理旧产物（可选但推荐）
      - name: Clean build
        run: flutter clean

      # 2) 关键步骤：用当前 Flutter 版本重建 Android 宿主（不动 Dart 代码）
      #    --org 与 --project-name 用于生成包名 com.example.buchouchi（和我们之前一致）
      - name: Regenerate Android host project
        run: |
          set -euo pipefail
          flutter --version
          flutter create . \
            --platforms=android \
            --org com.example \
            --project-name buchouchi \
            --overwrite

      # 3) 把应用名改回“ 不愁吃 ”（Flutter 模板默认会用 @string/app_name）
      - name: Set app name to Chinese
        run: |
          XML="android/app/src/main/res/values/strings.xml"
          if [ -f "$XML" ]; then
            sed -i 's#<string name="app_name">[^<]*</string>#<string name="app_name">不愁吃</string>#g' "$XML"
          fi

      # 4) 获取依赖并构建
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: buchouchi-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
