name: Android CI (Flutter)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Clean build
        run: flutter clean

      - name: Guard: ensure no Android v1 embedding
        run: |
          if grep -R "io.flutter.app" -n android/ ; then
            echo "Found deprecated v1 embedding import (io.flutter.app.*). Please remove them." >&2
            exit 1
          fi
          if grep -R "FlutterMain" -n android/ ; then
            echo "Found deprecated FlutterMain.* usage. Remove it." >&2
            exit 1
          fi

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: buchouchi-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
